# Module manifest for module testmodule

#
# Generated by: Jon S, Sabin IO
#
# Generated on: 05/03/2020
#
 
@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'testmodule.psm1'
 
    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules = @()
 
    # Version number of this module.
    ModuleVersion = '1.1'
 
    # ID used to uniquely identify this module
    GUID = 'bcc8282a-0550-4f5e-8cee-1a9f75d2308d'
 
    # Author of this module
    Author = 'Sabin.IO'
 
    # Company or vendor of this module
    CompanyName = 'Sabin.IO'
 
    # Copyright statement for this module
    Copyright = 'Sabin.IO 2020'
 
    # Description of the functionality provided by this module
    Description = 'Test module for testing module imports'
 
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = ''
 
    # Name of the Windows PowerShell host required by this module
    PowerShellHostName = ''
 
    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion = ''
 
    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''
 
    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = ''
 
    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture = ''
 
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()
 
    # Script files (.psm1) that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @()
 
    # Format files (.psm1xml) to be loaded when importing this module
    FormatsToProcess = @()
 
    # Functions to export from this module
    FunctionsToExport = '*'
    # Cmdlets to export from this module
    CmdletsToExport = '*'
 
    # Variables to export from this module
    VariablesToExport = '*'
 
    # Aliases to export from this module
    AliasesToExport = '*'
 
    # List of all modules packaged with this module
    ModuleList = @()
 
    # List of all files packaged with this module
    FileList = @()
 
    # Private data to pass to the module specified in ModuleToProcess
    PrivateData = ''
 
}
