jobs:
- job: Publish
  displayName: Publish
  pool:
    name: 'sio-build-agents'

  steps:
  - checkout: none   
  - task: PowerShell@2
    inputs:
      filePath: $(System.DefaultWorkingDirectory)/.build/pipeline-tasks.ps1
      arguments: -Install

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: $(ProjectName)
      path: $(artifactsPath)\$(ProjectName)

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'write-Host "##vso[task.setvariable variable=path;]$($env:localappdata)\Microsoft\dotnet;$($env:path)"'
      
  - task: PowerShell@2
    inputs:
      filePath: $(System.DefaultWorkingDirectory)/.build/pipeline-tasks.ps1
      arguments: -Install -Publish -PowershellRepositoryKey (Convertto-securestring $(NugetApiKey) -force -asplaintext)   
    displayName: 'Publish Module to PowerShell Gallery'