Function Write-Banner {

    Write-Host @'
####################################################################################################

Build and deploy

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyysNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh://mMMMMMMMMMMMMMMMMMNy++sNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh://mMMMMMMMMMMMMMMMMMm/::/hMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh://mMMMMMMMMMMMMMMMMMMmhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMNNMMMMMMMMMMMMh://mMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMMMMMMMMM
MMMMMMMMmyo+////++odMMMMMMy+++////+oymMMMMMMMh://yo+////+oymMMMMMMMMy++oNMMMMMho++///////+sdMMMMMMMM
MMMMMMMy///+osyssoodMMMMMMh+syyyys+///yMMMMMMh://:/+osso+/:/omMMMMMMs://NMMMMNo://ossyys+///omMMMMMM
MMMMMMN//:sNMMMMMMMMMMMMMMMMMMMMMMMy///dMMMMMh://hNMMMMMMd+///dMMMMMs://NMMMMNo::+MMMMMMMd//:oMMMMMM
MMMMMMN+:/+dNMMMMMMMMMMMMMMMMMMMMMMN+::sMMMMMh://mMMMMMMMMN+:/+NMMMMs://NMMMMNo::+MMMMMMMMy///NMMMMM
MMMMMMMmo////oydmMMMMMMMMMmhso+///+o//:sMMMMMh://mMMMMMMMMMy://dMMMMs://NMMMMNo::+MMMMMMMMd//:mMMMMM
MMMMMMMMMNdso//://smMMMMms///+ssssso//:sMMMMMh://mMMMMMMMMMy://dMMMMs://NMMMMNo::+MMMMMMMMd//:mMMMMM
MMMMMMMMMMMMMMmh+///hMMN+:/+mMMMMMMN+::sMMMMMh://mMMMMMMMMNo:/+NMMMMs://NMMMMNo::+MMMMMMMMd//:mMMMMM
MMMMMMMMMMMMMMMMN+::+MMN//:+NMMMMMMN+::sMMMMMh://mMMMMMMMNs://hMMMMMs://NMMMMNo::+MMMMMMMMd//:mMMMMM
MMMMMMNyydmNmmdhs///yMMMy///ohdmmmmd+::sMMMMMh://ydmmmdhs/::+dMMMMMMs://NMMMMNo::+MMMMMMMMd//:mMMMMM
MMMMMMm//::::::::/odMMMMMdo//:::::::::/sMMMMMh//:::::::://ohNMMMMMMMy///NMMMMNo//+MMMMMMMMm//:mMMMMM
MMMMMMMNmddhhhddmNMMMMMMMMMNmmddddmmmmNNMMMMMMNNmmmddddmmNMMMMMMMMMMNNNNMMMMMMmmmNMMMMMMMMMmmmMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                                                                                    
----------------------------------------------------------------------------------------------------
'@
}